apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tekton-generate
spec:
  inputs:
    params:
      - name: TEMPLATE_URLS
        type: array
        description: List of files to apply jinja template rendering to
      - name: TEMPLATE_VARS
        type: array
        description: |
          List of jinja template variables and values of the form
          var1, val1, var2, val2, ...
      - name: TEMPLATE_DIR
        description: Directory to place input template files
        default: template
      - name: RENDERED_DIR
        description: Directory to place output rendered templates
        default: rendered
      - name: TEKTON_JINJA_IMAGE
        description: Image to use for tekton jinja task
        default: # quay.io/erikerlandson/tekton-jinja:0.1.0
  workspaces:
    - name: output
      readOnly: false
      mountPath: /opt/tekton-generate/data
  steps:
    - name: stage-templates
      image: $(inputs.params.TEKTON_JINJA_IMAGE)
      command:
        - "/opt/tekton-generate/bin/stage"
        - "/opt/tekton-generate/data/$(inputs.params.TEMPLATE_DIR)"
        - "/opt/tekton-generate/data/$(inputs.params.RENDERED_DIR)"
        - "$(inputs.params.TEMPLATE_URLS[*])"
    - name: render-templates
      image: $(inputs.params.TEKTON_JINJA_IMAGE)
      command:
        - "/opt/tekton-generate/bin/render"
        - "/opt/tekton-generate/data/$(inputs.params.TEMPLATE_DIR)"
        - "/opt/tekton-generate/data/$(inputs.params.RENDERED_DIR)"
        - "--urls"
        - "$(inputs.params.TEMPLATE_URLS[*])"
        - "--vars"
        - "$(inputs.params.TEMPLATE_VARS[*])"
